import { z } from "zod";

const scheduleRow = z.object({
  time: z.string().min(1),
  action: z.string().min(1),
});

const weddingSchema = z.object({
  inquiryType: z.literal("wedding_website"),
  partner1FirstName: z.string().min(1).max(120),
  partner1LastName: z.string().min(1).max(120),
  partner2FirstName: z.string().min(1).max(120),
  partner2LastName: z.string().min(1).max(120),
  weddingDate: z.string().optional(),
  locationName: z.string().min(1).max(500),
  locationLat: z.string().optional(),
  locationLng: z.string().optional(),
  weddingVenueName: z.string().max(300).optional(),
  weddingVenuePostalCode: z.string().max(20).optional(),
  weddingVenueCity: z.string().max(120).optional(),
  weddingVenueStreet: z.string().max(200).optional(),
  weddingVenueMapLink: z.string().max(500).optional(),
  ceremonyType: z.enum(["church", "civil", "outdoor", "other"]).optional(),
  ceremonyName: z.string().max(300).optional(),
  ceremonyPostalCode: z.string().max(20).optional(),
  ceremonyCity: z.string().max(120).optional(),
  ceremonyStreet: z.string().max(200).optional(),
  ceremonyMapLink: z.string().max(500).optional(),
  ceremonyOtherDetails: z.string().max(3000).optional(),
  travelDetails: z.string().max(3000).optional(),
  colorPalette: z.string().max(2000).optional(),
  themes: z.string().max(2000).optional(),
  templateName: z.string().max(120).optional(),
  heroPhotoName: z.string().max(260).optional(),
  inspirationFilesNames: z.array(z.string().max(260)).max(3).default([]),
  clientEmail: z.string().email().max(320),
  clientPhone: z.string().max(40).optional(),
  schedule: z.array(scheduleRow).default([]),
  schedulePreferences: z.string().max(3000).optional(),
  scheduleSuggestions: z.array(z.string().max(80)).max(12).default([]),
  accommodationNote: z.string().max(5000).optional(),
  overnightTransportNote: z.string().max(3000).optional(),
  afterpartyNote: z.string().max(3000).optional(),
  guestInfoNote: z.string().max(5000).optional(),
  rsvpEnabled: z.boolean().default(false),
  rsvpDeadline: z.string().max(500).optional(),
  rsvpNotes: z.string().max(2000).optional(),
  extraNotes: z.string().max(8000).optional(),
  contactFullName: z.string().max(160).optional(),
  contactMessage: z.string().max(8000).optional(),
});

const contactSchema = z.object({
  inquiryType: z.literal("contact"),
  contactFullName: z.string().min(1).max(160),
  clientEmail: z.string().email().max(320),
  clientPhone: z.string().max(40).optional(),
  contactMessage: z.string().min(1).max(8000),
  partner1FirstName: z.string().max(120).optional(),
  partner1LastName: z.string().max(120).optional(),
  partner2FirstName: z.string().max(120).optional(),
  partner2LastName: z.string().max(120).optional(),
  weddingDate: z.string().optional(),
  locationName: z.string().max(500).optional(),
  locationLat: z.string().optional(),
  locationLng: z.string().optional(),
  weddingVenueName: z.string().max(300).optional(),
  weddingVenuePostalCode: z.string().max(20).optional(),
  weddingVenueCity: z.string().max(120).optional(),
  weddingVenueStreet: z.string().max(200).optional(),
  weddingVenueMapLink: z.string().max(500).optional(),
  ceremonyType: z.enum(["church", "civil", "outdoor", "other"]).optional(),
  ceremonyName: z.string().max(300).optional(),
  ceremonyPostalCode: z.string().max(20).optional(),
  ceremonyCity: z.string().max(120).optional(),
  ceremonyStreet: z.string().max(200).optional(),
  ceremonyMapLink: z.string().max(500).optional(),
  ceremonyOtherDetails: z.string().max(3000).optional(),
  travelDetails: z.string().max(3000).optional(),
  colorPalette: z.string().max(2000).optional(),
  themes: z.string().max(2000).optional(),
  templateName: z.string().max(120).optional(),
  heroPhotoName: z.string().max(260).optional(),
  inspirationFilesNames: z.array(z.string().max(260)).max(3).default([]),
  schedule: z.array(scheduleRow).default([]),
  schedulePreferences: z.string().max(3000).optional(),
  scheduleSuggestions: z.array(z.string().max(80)).max(12).default([]),
  accommodationNote: z.string().max(5000).optional(),
  overnightTransportNote: z.string().max(3000).optional(),
  afterpartyNote: z.string().max(3000).optional(),
  guestInfoNote: z.string().max(5000).optional(),
  rsvpEnabled: z.boolean().default(false),
  rsvpDeadline: z.string().max(500).optional(),
  rsvpNotes: z.string().max(2000).optional(),
  extraNotes: z.string().max(8000).optional(),
});

export const inquiryFormSchema = z.discriminatedUnion("inquiryType", [
  weddingSchema,
  contactSchema,
]);

export type InquiryFormInput = z.infer<typeof inquiryFormSchema>;
