ALTER TABLE "inquiries" ADD COLUMN "inquiry_type" text DEFAULT 'wedding_website' NOT NULL;
ALTER TABLE "inquiries" ADD COLUMN "wedding_venue_name" text;
ALTER TABLE "inquiries" ADD COLUMN "wedding_venue_postal_code" text;
ALTER TABLE "inquiries" ADD COLUMN "wedding_venue_city" text;
ALTER TABLE "inquiries" ADD COLUMN "wedding_venue_street" text;
ALTER TABLE "inquiries" ADD COLUMN "wedding_venue_map_link" text;
ALTER TABLE "inquiries" ADD COLUMN "ceremony_type" text;
ALTER TABLE "inquiries" ADD COLUMN "ceremony_name" text;
ALTER TABLE "inquiries" ADD COLUMN "ceremony_postal_code" text;
ALTER TABLE "inquiries" ADD COLUMN "ceremony_city" text;
ALTER TABLE "inquiries" ADD COLUMN "ceremony_street" text;
ALTER TABLE "inquiries" ADD COLUMN "ceremony_map_link" text;
ALTER TABLE "inquiries" ADD COLUMN "ceremony_other_details" text;
ALTER TABLE "inquiries" ADD COLUMN "travel_details" text;
ALTER TABLE "inquiries" ADD COLUMN "template_name" text;
ALTER TABLE "inquiries" ADD COLUMN "hero_photo_name" text;
ALTER TABLE "inquiries" ADD COLUMN "inspiration_files_names" jsonb DEFAULT '[]'::jsonb;
ALTER TABLE "inquiries" ADD COLUMN "schedule_preferences" text;
ALTER TABLE "inquiries" ADD COLUMN "schedule_suggestions" jsonb DEFAULT '[]'::jsonb;
ALTER TABLE "inquiries" ADD COLUMN "overnight_transport_note" text;
ALTER TABLE "inquiries" ADD COLUMN "afterparty_note" text;
ALTER TABLE "inquiries" ADD COLUMN "guest_info_note" text;
ALTER TABLE "inquiries" ADD COLUMN "rsvp_notes" text;
ALTER TABLE "inquiries" ADD COLUMN "contact_full_name" text;
ALTER TABLE "inquiries" ADD COLUMN "contact_message" text;
